import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime

from sklearn.metrics import accuracy_score, mean_squared_error, r2_score

from docx import Document
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table
from reportlab.lib.styles import getSampleStyleSheet

import pypandoc


# ---------------------------------------------------------
# REPORT HEADER
# ---------------------------------------------------------

def report_header(title):

    header = f"""
StatX Statistical Analysis Report

Title: {title}
Generated by: StatX Automatic Report Generator
Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}
"""

    return header


# ---------------------------------------------------------
# DATASET SUMMARY
# ---------------------------------------------------------

def dataset_summary(df):

    summary = df.describe().transpose()

    missing = df.isnull().sum()

    table = pd.DataFrame({
        "Mean":summary["mean"],
        "Std":summary["std"],
        "Min":summary["min"],
        "Max":summary["max"],
        "Missing":missing
    })

    return table


# ---------------------------------------------------------
# REGRESSION REPORT
# ---------------------------------------------------------

def regression_report(model, X, Y, predictions):

    mse = mean_squared_error(Y, predictions)
    r2 = r2_score(Y, predictions)

    report = {}

    report["MSE"] = mse
    report["R2"] = r2

    return report


# ---------------------------------------------------------
# HYPOTHESIS TEST REPORT
# ---------------------------------------------------------

def hypothesis_report(test_name, statistic, pvalue, alpha=0.05):

    if pvalue < alpha:

        decision = "Reject H0"

        interpretation = f"""
The p-value ({pvalue:.4f}) is smaller than the significance level ({alpha}).
Therefore, the null hypothesis is rejected.
"""

    else:

        decision = "Fail to Reject H0"

        interpretation = f"""
The p-value ({pvalue:.4f}) is larger than the significance level ({alpha}).
There is insufficient evidence to reject the null hypothesis.
"""

    report = {

        "Test":test_name,
        "Statistic":statistic,
        "p-value":pvalue,
        "Decision":decision,
        "Interpretation":interpretation

    }

    return report


# ---------------------------------------------------------
# MACHINE LEARNING REPORT
# ---------------------------------------------------------

def ml_report(y_true, y_pred):

    acc = accuracy_score(y_true, y_pred)

    if acc > 0.9:

        quality = "Excellent predictive performance"

    elif acc > 0.8:

        quality = "Very good predictive performance"

    elif acc > 0.7:

        quality = "Acceptable predictive performance"

    else:

        quality = "Weak predictive performance"

    report = {

        "Accuracy":acc,
        "Interpretation":quality

    }

    return report


# ---------------------------------------------------------
# GRAPH GENERATION
# ---------------------------------------------------------

def create_graphs(df):

    figures = []

    numeric = df.select_dtypes(include=np.number).columns

    for col in numeric[:4]:

        fig, ax = plt.subplots()

        sns.histplot(df[col], kde=True)

        ax.set_title(f"Distribution of {col}")

        figures.append(fig)

    return figures


# ---------------------------------------------------------
# TEXT REPORT BUILDER
# ---------------------------------------------------------

def build_text_report(title, df, regression=None, hypothesis=None, ml=None):

    text = report_header(title)

    text += "\n\nDATASET SUMMARY\n"

    text += df.describe().to_string()

    if regression:

        text += "\n\nREGRESSION RESULTS\n"

        for k,v in regression.items():

            text += f"\n{k}: {v}"

    if hypothesis:

        text += "\n\nHYPOTHESIS TEST RESULTS\n"

        for k,v in hypothesis.items():

            text += f"\n{k}: {v}"

    if ml:

        text += "\n\nMACHINE LEARNING RESULTS\n"

        for k,v in ml.items():

            text += f"\n{k}: {v}"

    text += "\n\nConclusion:\n"

    text += """
The analysis was performed using the StatX statistical system.
Results should be interpreted within the context of the research problem.
"""

    return text


# ---------------------------------------------------------
# EXPORT WORD
# ---------------------------------------------------------

def export_word(report_text):

    doc = Document()

    for line in report_text.split("\n"):

        doc.add_paragraph(line)

    path = "statx_report.docx"

    doc.save(path)

    return path


# ---------------------------------------------------------
# EXPORT PDF
# ---------------------------------------------------------

def export_pdf(report_text):

    styles = getSampleStyleSheet()

    story = []

    for line in report_text.split("\n"):

        story.append(Paragraph(line, styles["Normal"]))

        story.append(Spacer(1,8))

    path = "statx_report.pdf"

    pdf = SimpleDocTemplate(path)

    pdf.build(story)

    return path


# ---------------------------------------------------------
# EXPORT LATEX
# ---------------------------------------------------------

def export_latex(report_text):

    path = "statx_report.tex"

    pypandoc.convert_text(
        report_text,
        "latex",
        format="md",
        outputfile=path,
        extra_args=['--standalone']
    )

    return path


# ---------------------------------------------------------
# STREAMLIT INTERFACE
# ---------------------------------------------------------

def run(df):

    st.title("StatX Automatic Statistical Report Generator")

    if df is None:

        st.warning("Upload dataset first")

        return

    st.subheader("Dataset Preview")

    st.dataframe(df.head())

    title = st.text_input("Report Title","Statistical Analysis Report")

    report_type = st.multiselect(

        "Select Report Sections",

        [

            "Dataset Summary",

            "Regression Report",

            "Hypothesis Test",

            "Machine Learning"
        ]

    )

    regression = None
    hypothesis = None
    ml = None

    if "Regression Report" in report_type:

        st.subheader("Regression Input")

        y = st.selectbox("Dependent Variable", df.columns)

        x = st.multiselect("Predictors", df.columns)

        if st.button("Run Regression"):

            from sklearn.linear_model import LinearRegression

            X = df[x]

            Y = df[y]

            model = LinearRegression()

            model.fit(X,Y)

            pred = model.predict(X)

            regression = regression_report(model,X,Y,pred)

            st.write(regression)

    if "Hypothesis Test" in report_type:

        st.subheader("Hypothesis Test")

        stat = st.number_input("Test Statistic")

        pval = st.number_input("p-value")

        if st.button("Interpret Test"):

            hypothesis = hypothesis_report(

                "Generic Test",
                stat,
                pval

            )

            st.write(hypothesis)

    if "Machine Learning" in report_type:

        st.subheader("ML Results")

        acc = st.slider("Accuracy",0.0,1.0,0.8)

        ml = {

            "Accuracy":acc,
            "Interpretation":ml_report(
                [1,1,1],
                [1,1,1]
            )["Interpretation"]
        }

        st.write(ml)

    if st.button("Generate Full Report"):

        report_text = build_text_report(

            title,
            df,
            regression,
            hypothesis,
            ml
        )

        st.subheader("Generated Report")

        st.text(report_text)

        st.download_button(

            "Download TXT",

            report_text,

            file_name="statx_report.txt"

        )

        if st.button("Export Word"):

            path = export_word(report_text)

            st.success(f"Saved: {path}")

        if st.button("Export PDF"):

            path = export_pdf(report_text)

            st.success(f"Saved: {path}")

        if st.button("Export LaTeX"):

            path = export_latex(report_text)

            st.success(f"Saved: {path}")
